export const allPossibleCountries = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei ",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Côte d'Ivoire",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo (Congo-Brazzaville)",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czechia (Czech Republic)",
    "Democratic Republic of the Congo",
    "Denmark",
    "Djibouti",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Swaziland",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Holy See",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar (formerly Burma)",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Korea",
    "North Macedonia",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine State",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Korea",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor-Leste",
    // "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States of America",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe",
];

export const mostPopularCities = [
    "Tokyo",
    "Delhi",
    "Shanghai",
    "Dhaka",
    "Sao Paulo",
    "Mexico City",
    "Cairo",
    "Beijing",
    "Mumbai",
    "Osaka",
    "Chongqing",
    "Karachi",
    "Istanbul",
    "Kinshasa",
    "Lagos",
    "Buenos Aires",
    "Kolkata",
    "Manila",
    "Tianjin",
    "Guangzhou",
    "Rio de Janeiro",
    "Lahore",
    "Bangalore",
    "Shenzhen",
    "Moscow",
    "Chennai",
    "Bogota",
    "Paris",
    "Jakarta",
    "Lima",
    "Bangkok",
    "Hyderabad",
    "Seoul",
    "Nagoya",
    "London",
    "Chengdu",
    "Nanjing",
    "Tehran",
    "Ho Chi Minh City",
    "Luanda",
    "New York City",
    "Wuhan",
    "Xi-an Shaanxi",
    "Ahmedabad",
    "Kuala Lumpur",
    "Hangzhou",
    // "Surat",
    "Suzhou",
    "Hong Kong",
    "Riyadh",
    "Shenyang",
    "Baghdad",
    "Dongguan",
    "Foshan",
    "Dar es Salaam",
    "Pune",
    "Santiago",
    "Madrid",
    "Haerbin",
    "Toronto",
    "Belo Horizonte",
    "Khartoum",
    "Johannesburg",
    "Singapore",
    "Dalian",
    "Qingdao",
    "Zhengzhou",
    "Ji-nan Shandong",
    "Barcelona",
    "Saint Petersburg",
    "Abidjan",
    "Yangon",
    "Fukuoka",
    "Alexandria",
    "Guadalajara",
    "Ankara",
    "Chittagong",
    "Addis Ababa",
    "Melbourne",
    "Nairobi",
    "Hanoi",
    "Sydney",
    "Monterrey",
    "Changsha",
    "Brasilia",
    "Cape Town",
    "Jiddah",
    "Urumqi",
    "Kunming",
    "Changchun",
    "Hefei",
    "Shantou",
    "Xinbei",
    "Kabul",
    "Ningbo",
    "Tel Aviv",
    "Yaounde",
    "Rome",
    "Shijiazhuang",
    "Montreal",
    "Recife",
    //"Kano",
    "Porto Alegre",
    "Fortaleza",
    "Jaipur",
    "Nanning",
    "Medellin",
    "Taiyuan Shanxi",
    "Ekurhuleni",
    "Douala",
    "Kozhikode",
    "Salvador",
    "Los Angeles",
    "Changzhou",
    "Xiamen",
    "Lucknow",
    "Fuzhou Fujian",
    "Casablanca",
    "Wenzhou",
    "Nanchang",
    "Malappuram",
    "Curitiba",
    "Ibadan",
    "Antananarivo",
    "Tangshan Hebei",
    "Abuja",
    "Kampala",
    "Kumasi",
    "Faisalabad",
    "Bekasi",
    "Berlin",
    "Guiyang",
    "Busan",
    "Santo Domingo",
    "Asuncion",
    "Campinas",
    "Wuxi",
    "Thrissur",
    "Dakar",
    "Port Harcourt",
    "Mashhad",
    "Kochi",
    "Puebla",
    "Kuwait City",
    "Lanzhou",
    "Indore",
    "Durban",
    "Kanpur",
    "Sanaa",
    "Athens",
    "Milan",
    "Pyongyang",
    "Guayaquil",
    "Izmir",
    "Ouagadougou",
    "Lusaka",
    "Guatemala City",
    "Kiev",
    "Surabaya",
    "Nagpur",
    "Lisbon",
    "Zhongshan",
    "Dubai",
    "Caracas",
    "Depok",
    "Shizuoka",
    "Coimbatore",
    "Handan",
    "Port-au-Prince",
    "Huaian",
    "Algiers",
    "Weifang",
    "Incheon",
    "Bamako",
    "Goiania",
    "Thiruvananthapuram",
    "Manchester",
    "Mbuji-Mayi",
    "Chicago",
    "Taipei",
    "Pretoria",
    "Zibo",
    "Shaoxing",
    "Lubumbashi",
    "Yantai",
    "Huizhou",
    "Sapporo",
    "Birmingham",
    "Bandung",
    "Vancouver",
    "Accra",
    "Toluca de Lerdo",
    "Tashkent",
    "Brazzaville",
    "Luoyang",
    "Patna",
    "Bhopal",
    "Damascus",
    "Mogadishu",
    "Brisbane",
    "Tangerang",
    "San Juan",
    "Tunis",
    "Beirut",
    "Nantong",
    "Medan",
    "Baku",
    "Belem",
    "Gujranwala",
    "Houston",
    "Peshawar",
    "Manaus",
    "Sendai",
    "Maracaibo",
    "Rawalpindi",
    "Barranquilla",
    "Hohhot",
    "Taoyuan",
    "Baotou",
    "Kannur",
    "Liuzhou",
    "Visakhapatnam",
    "Vadodara",
    "Xuzhou",
    "Tijuana",
    "Esfahan",
    "Phnom Penh",
    "Amman",
    "Daegu",
    "Naples",
    "Nashik",
    "Vijayawada",
    "Havana",
    "Grande Vitoria",
    "Mecca",
    "Brussels",
    "Multan",
    "Aleppo",
    "Putian",
    "Perth",
    "Yangzhou",
    "Hiroshima",
    "Baoding",
    "Bursa",
    "Taizhou Zhejiang",
    "Minsk",
    "Conakry",
    "Wuhu Anhui",
    "Linyi Shandong",
    "Kollam",
    "Rajkot",
    "Haikou",
    "Vienna",
    "Valencia",
    "Almaty",
    "Daqing",
    "Yancheng Jiangsu",
    "Panama City",
    "Semarang",
    "Lianyungang",
    "Rabat",
    "Baixada Santista",
    "Quito",
    "Hyderabad",
    "Lome",
    "Ludhiana",
    "West Yorkshire",
    "Davao City",
    "La Paz",
    "Leon de los Aldamas",
    "Zhuhai",
    "Benin City",
    "Datong",
    "Quanzhou",
    "Adana",
    "Madurai",
    "Turin",
    "Matola",
    "Warsaw",
    "Hamburg",
    "Can Tho",
    "Sharjah",
    "Bucharest",
    "Palembang",
    "Santa Cruz",
    "Budapest",
    "Gaziantep",
    "Montevideo",
    "Meerut",
    "Raipur",
    "Lyon",
    "Jiangmen",
    "Mosul",
    "Cixi",
    "La Laguna",
    "Varanasi",
    "Xiangyang",
    "Shiraz",
    "Glasgow",
    "Novosibirsk",
    "Batam",
    "Stockholm",
    "Yinchuan",
    "Anshan",
    "Jamshedpur",
    "Yichang",
    "Srinagar",
    "Auckland",
    "Jilin",
    "Ulaanbaatar",
    "Tabriz",
    "Makassar",
    "Aurangabad",
    "Phoenix",
    "Qinhuangdao",
    "Xining",
    "Muscat",
    "Monrovia",
    "Marseille",
    "Tiruppur",
    "Philadelphia",
    "Hengyang",
    "Calgary",
    "Qiqihaer",
    "Cordoba",
    "Suqian",
    "Kananga",
    "Karaj",
    "Anyang",
    "Rosario",
    "Daejon",
    "Munich",
    "Ciudad Juarez",
    "Harare",
    "Onitsha",
    "Jodhpur",
    "Gaoxiong",
    "Medina",
    "Jining Shandong",
    "Abu Dhabi",
    "N-Djamena",
    "Tegucigalpa",
    "Gwangju",
    "Yekaterinburg",
    "Kathmandu",
    "Edmonton",
    "Natal",
    "Grande Sao Luis",
    "Ranchi",
    "Zhangjiakou",
    "Mandalay",
    "Jabalpur",
    "Huainan",
    "Asansol",
    "Kota",
    "Chaozhou",
    "San Antonio",
    "Gwalior",
    "San Jose",
    "Allahabad",
    "Yiwu",
    "Chon Buri",
    "Nouakchott",
    "Amritsar",
    "Kharkiv",
    "Ottawa",
    "Zurich",
    "Taizhou Jiangsu",
    "Basra",
    "Joao Pessoa",
    "Ganzhou",
    "Belgrade",
    "San Diego",
    "Homs",
    "Taian Shandong",
    "Weihai",
    "Queretaro",
    "Mombasa",
    "Niamey",
    "Konya",
    "Hai Phong",
    "Jiaxing",
    "Copenhagen",
    "Cochabamba",
    "Dhanbad",
    "Kisangani",
    "Bucaramanga",
    "Kaifeng",
    "Adelaide",
    "Taizhong",
    "Rizhao",
    "Maceio",
    "Suweon",
    "Dongying",
    "Zunyi",
    "Zhanjiang",
    "Samut Prakan",
    "Nanchong",
    "Joinville",
    "Qom",
    "Helsinki",
    "Mianyang Sichuan",
    "Dallas",
    "Liuan",
    "Porto",
    "Antalya",
    "Shiyan",
    "Prague",
    "Bareilly",
    "Liuyang",
    "Ad-Dammam",
    "Fushun Liaoning",
    "Pointe-Noire",
    "Yingkou",
    "Sofia",
    "Kazan",
    "Tengzhou",
    "Port Elizabeth",
    "Aligarh",
    "Ahvaz",
    "Florianopolis",
    "Tanger",
    "Freetown",
    "Maoming",
    "Pekan Baru",
    "Moradabad",
    "Suzhou",
    "Uyo",
    "Mysore",
    "Dublin",
    "San Luis Potosi",
    "Astana",
    "Nizhniy Novgorod",
    "Ruian",
    "Mwanza",
    "Durg-Bhilainagar",
    "Barquisimeto",
    "Jieyang",
    "Chelyabinsk",
    "Zhuzhou",
    "Baoji",
    "Maracay",
    "Bhubaneswar",
    "Pingdingshan Henan",
    "Zhenjiang Jiangsu",
    "Chifeng",
    "Puning",
    "Lilongwe",
    "Jinhua",
    "Mendoza",
    "Kigali",
    "Bogor",
    "Huaibei",
    "Merida",
    "Tiruchirappalli",
    "Islamabad",
    "Chiang Mai",
    "Nanyang Henan",
    "Xiangtan Hunan",
    "Benxi",
    "Jinzhou",
    "Chandigarh",
    "Bukavu",
    "Abomey-Calavi",
    "Da Nang",
    "Liupanshui",
    "Omsk",
    "Nnewi",
    "Tripoli",
    "Guilin",
    "Amsterdam",
    "Tasikmalaya",
    "Haifa",
    "Binzhou",
    "Pizhou",
    "Quetta",
    "Mexicali",
    "Krasnoyarsk",
    "Hubli-Dharwad",
    "Kaduna",
    "Samara",
    "Guwahati",
    "Luohe",
    "Salem",
    "Aguascalientes",
    "Ufa",
    "Bujumbura",
    "Maputo",
    "Bandar Lampung",
    "Rostov-on-Don",
    "Cologne",
    "Yueqing",
    "Saharanpur",
    "Shimkent",
    "Yongin",
    "Xinxiang",
];

/*
        // JSON.stringify(Array.from(document.querySelectorAll("a[href^='/p']")).map((x) => x.href))
        // swiss: ["https://www.instagram.com/p/Cno_rQ0KPq5/","https://www.instagram.com/p/CnrpkPxLALQ/","https://www.instagram.com/p/CidODn8rbzd/","https://www.instagram.com/p/CjANW5IoZ0K/","https://www.instagram.com/p/CjGRiXJoNkp/","https://www.instagram.com/p/CjPiLbHI19I/","https://www.instagram.com/p/CnESev4JeGf/","https://www.instagram.com/p/CnpWBKHJU7R/","https://www.instagram.com/p/CnSTv5-JSaj/","https://www.instagram.com/p/CegS2lvj-sS/","https://www.instagram.com/p/Cmy5DihvtSr/","https://www.instagram.com/p/CnUbz3ZLHGn/","https://www.instagram.com/p/Cm4DIL8IL1d/"]'
        // swiss2: '["https://www.instagram.com/p/Ck0rXb4jLPs/","https://www.instagram.com/p/CloYRUuI1bF/","https://www.instagram.com/p/Ci66zEUIqni/","https://www.instagram.com/p/CizQePPoLs9/","https://www.instagram.com/p/B9reNaRh8HO/","https://www.instagram.com/p/B8EkxiIBenV/","https://www.instagram.com/p/B6VT552hnpU/","https://www.instagram.com/p/B8bKtbHDv0P/","https://www.instagram.com/p/B3nwXhTAKLR/","https://www.instagram.com/p/BsrOyfYA7j4/","https://www.instagram.com/p/BzHSJ55AbQi/","https://www.instagram.com/p/B8V_suFFm6X/","https://www.instagram.com/p/B2w8mHVC7dB/","https://www.instagram.com/p/BxyuZhSHe0cftNPqgwBSX_dnO4fKxC7Yzg0uI80/","https://www.instagram.com/p/ByEy3SrnwTKmY-_EDWAvDSzVA2oKeoqKVFEOhM0/","https://www.instagram.com/p/ByFSx4ynk3g_jh4ehlP4pEC3XuaCFVa6byGpFk0/","https://www.instagram.com/p/ByIL_FNn_itUFtPJdk5X4nFIs074QKhpQcDYOs0/","https://www.instagram.com/p/ByKCy4BngsYPj9NQxZ_3s_Ykj4AGikfYWfWnII0/","https://www.instagram.com/p/ByKYdvrnJT2rCjj3yluwLh5H0oiReNLRn9hSsw0/","https://www.instagram.com/p/ByNg60NH9cS74bOzZllZq4WI4QqY2jqQX_Gy8Q0/","https://www.instagram.com/p/ByU1V5FHCxrRdqFw2KjBphpzJU-Bx9o_2flCkc0/"]'
        // swiss3: '["https://www.instagram.com/p/B8EkxiIBenV/","https://www.instagram.com/p/B8RhHY3BoUw/","https://www.instagram.com/p/B8Rkic1B5mB/","https://www.instagram.com/p/B8UJg2WB_IU/"]'
        // mexico: ["https://www.instagram.com/p/Cm9SAp8DqL3/","https://www.instagram.com/p/Cl7iPWDDX-E/"]
        // china: '["https://www.instagram.com/p/CoDcIHvgf6K/"]'
        // paris: '["https://www.instagram.com/p/CneRc2IhEJ_/","https://www.instagram.com/p/CnZkhlAPsDD/","https://www.instagram.com/p/Cj5HWZlIt1N/","https://www.instagram.com/p/B2L_mOeAm_1/","https://www.instagram.com/p/B2SKHwCIUH7/","https://www.instagram.com/p/BvUp7SWn6CO/","https://www.instagram.com/p/BwXfpxjndnE/","https://www.instagram.com/p/B2Zu5WuBLyW/","https://www.instagram.com/p/B2XKvzsie1T/","https://www.instagram.com/p/B2W3PzZAshw/","https://www.instagram.com/p/B2WcGUkIReT/","https://www.instagram.com/p/B2YYkGziYks/","https://www.instagram.com/p/B2PKgkAoTRg/","https://www.instagram.com/p/B2RuvR7BLzl/","https://www.instagram.com/p/B167KYpCpFp/","https://www.instagram.com/p/B2SXXH2I_A9/","https://www.instagram.com/p/B2HHgsOIk5C/","https://www.instagram.com/p/B2TbMl1IK5X/","https://www.instagram.com/p/B19X7C4CaeQ/","https://www.instagram.com/p/B2UPzlDFjR3/","https://www.instagram.com/p/B19Zxf4oFzc/","https://www.instagram.com/p/B2UeS2ChWVx/","https://www.instagram.com/p/B1_zL4tokgx/","https://www.instagram.com/p/B2CV3emAgOB/","https://www.instagram.com/p/B2GfziohaWC/","https://www.instagram.com/p/B2Oba1IDpi3/","https://www.instagram.com/p/B2RGCfRoGgh/","https://www.instagram.com/p/B2MeVZEolQP/","https://www.instagram.com/p/B2JUrnEIRVV/","https://www.instagram.com/p/B2PMM2JFZ8k/","https://www.instagram.com/p/B2WXbigi_An/","https://www.instagram.com/p/B2FRZcQC84D/","https://www.instagram.com/p/B2QuH7DIuPn/","https://www.instagram.com/p/B2FeOmhH_Hp/","https://www.instagram.com/p/B2PPpa-pi86/"]'
        // hawaii: '["https://www.instagram.com/p/CnDNBK2OWRc/","https://www.instagram.com/p/CgJcuhosMhb/","https://www.instagram.com/p/CB5j4HQDaKz/","https://www.instagram.com/p/B-9FgbgDlwH/","https://www.instagram.com/p/B60xeNPDEV4/","https://www.instagram.com/p/B3lCBvKIah0/","https://www.instagram.com/p/B3howWAH4cT/","https://www.instagram.com/p/B3nIvA9HeBc/"]'
        // philipines: '["https://www.instagram.com/p/Cn4jKihOVxu/","https://www.instagram.com/p/CnpG43oAtdQ/","https://www.instagram.com/p/CSY3UfSLHZC/","https://www.instagram.com/p/CFRnrYjjZkz/","https://www.instagram.com/p/CAv4sAIjUlz/","https://www.instagram.com/p/B1yQQHYlFIC/","https://www.instagram.com/p/B2EJhfrlIvh/","https://www.instagram.com/p/Bzk7Hu3nszv/","https://www.instagram.com/p/Bz0ijMunsCb/","https://www.instagram.com/p/B2ZMnSllPAw/"]'
        // greece: '["https://www.instagram.com/p/Cn4RzuPoq1y/"]'
        // maldives: '["https://www.instagram.com/p/Cnpm6atgrto/","https://www.instagram.com/p/CfcKBv6sdq7/","https://www.instagram.com/p/Bqu0r9BBwG4/","https://www.instagram.com/p/B7dMTmHjNc4/","https://www.instagram.com/p/B3fAE99gnFd/","https://www.instagram.com/p/BzQSyIMnHS9/","https://www.instagram.com/p/B3gxCouhngx/","https://www.instagram.com/p/B3KITN5BgMw/","https://www.instagram.com/p/B2mFNmOhzIV/","https://www.instagram.com/p/B1nj9zug9j8/","https://www.instagram.com/p/B2RPh_ggCnY/","https://www.instagram.com/p/B2ZIj7PB8L6/","https://www.instagram.com/p/B2QAHT5I092/","https://www.instagram.com/p/B2J73GGhQCO/","https://www.instagram.com/p/BzgYSLdH_Oj/","https://www.instagram.com/p/BziTzZHns83/","https://www.instagram.com/p/BzndZJ7Hujf/","https://www.instagram.com/p/B1eHUWdgOmq/","https://www.instagram.com/p/B1iilCxAygW/","https://www.instagram.com/p/BziTzZHns83/","https://www.instagram.com/p/B7dMTmHjNc4/","https://www.instagram.com/p/BzQSyIMnHS9/","https://www.instagram.com/p/Bqu0r9BBwG4/","https://www.instagram.com/p/CfhCyotpfBS/","https://www.instagram.com/p/CfMpPg2sAgp/","https://www.instagram.com/p/CdaGP_ALWjb/","https://www.instagram.com/p/CdGc4L_pw21/","https://www.instagram.com/p/CfI9keGh-9a/","https://www.instagram.com/p/ChKf7bRoqyd/","https://www.instagram.com/p/ChxIwFtIjPq/","https://www.instagram.com/p/Camb_sIpO-C/","https://www.instagram.com/p/CgoY1D7qBBQ/","https://www.instagram.com/p/CjvsWisKt31/","https://www.instagram.com/p/CkfqEv1rOFl/","https://www.instagram.com/p/ClRDotgIevw/","https://www.instagram.com/p/CUiDH2oh1QV/","https://www.instagram.com/p/CcpxE6kJ9qG/","https://www.instagram.com/p/CdrRuZcrqOc/","https://www.instagram.com/p/Ce1IVVcLPB1/","https://www.instagram.com/p/CfYkV9yhi7E/","https://www.instagram.com/p/CfI9keGh-9a/","https://www.instagram.com/p/CYfEehkD-1C/","https://www.instagram.com/p/CZxHt5xNQUV/","https://www.instagram.com/p/Cc1gI4rpY4o/","https://www.instagram.com/p/CdGc4L_pw21/","https://www.instagram.com/p/CdaGP_ALWjb/","https://www.instagram.com/p/CdgBAProsJv/","https://www.instagram.com/p/CdvOLCYjrdM/","https://www.instagram.com/p/CeQda5qMOpx/","https://www.instagram.com/p/Ce0_9OdAmto/","https://www.instagram.com/p/CfJBpW9LqnL/","https://www.instagram.com/p/CfJ3V4bpZUS/","https://www.instagram.com/p/CfI8yGTh0dO/","https://www.instagram.com/p/CfEM3bBBqHF/","https://www.instagram.com/p/CfNujp8hzs1/","https://www.instagram.com/p/CfMpPg2sAgp/","https://www.instagram.com/p/CfUlDtJDHm4/","https://www.instagram.com/p/CfUPnlmKqTq/","https://www.instagram.com/p/CfbBBgoNudY/","https://www.instagram.com/p/Cfbx9Y5MC6u/","https://www.instagram.com/p/CfiRIUfDsak/","https://www.instagram.com/p/CfjTwexhF5F/","https://www.instagram.com/p/CfhCyotpfBS/","https://www.instagram.com/p/CfzM1hOj1gw/"]'
        // maoricios: '["https://www.instagram.com/p/CniuNCLPJ-S/"]'
        // fiji: '["https://www.instagram.com/p/CnhOUQ9qVRY/","https://www.instagram.com/p/CnXsQOCMig6/","https://www.instagram.com/p/CloMMk5sfHP/","https://www.instagram.com/p/ChRGGG-MF0W/","https://www.instagram.com/p/CmvR_5mMyO5/","https://www.instagram.com/p/Cm7CGclh91t/"]'
        // italy: '["https://www.instagram.com/p/CnfGBIxhAxa/","https://www.instagram.com/p/CnckxNqhOUH/","https://www.instagram.com/p/CnaRNc0gRxk/","https://www.instagram.com/p/ChQOZHpDBwe/","https://www.instagram.com/p/ChtHuMDs3Mc/","https://www.instagram.com/p/Cmy3G79hA0q/","https://www.instagram.com/p/CmPDhKHIxN_/"]'
        // italy2: '["https://www.instagram.com/p/B3O5svineQg/"]'
        // dubai: '["https://www.instagram.com/p/CnepSeRhZQs/","https://www.instagram.com/p/CnTttLxBuB-/","https://www.instagram.com/p/CnRq8Y_hGQO/","https://www.instagram.com/p/CnJwm2ahet1/","https://www.instagram.com/p/Cg8aGLzDZA9/"]'
        // singapure: '["https://www.instagram.com/p/CnZXVuDqme8/","https://www.instagram.com/p/B8JrIO7DRav/","https://www.instagram.com/p/Bxcb7oxHk2W/","https://www.instagram.com/p/B3L5lU9I7MS/","https://www.instagram.com/p/B2ykVJUn8Qh/"]'
        // santorini: '["https://www.instagram.com/p/CnZU1OYBKjx/","https://www.instagram.com/p/CiPt06moctE/","https://www.instagram.com/p/Ch9TfiuoAe5/","https://www.instagram.com/p/ChrKcLtIrMO/","https://www.instagram.com/p/ChwRUUqIdbu/","https://www.instagram.com/p/Bzn6Hatnxnq/"]'
        // finland: '["https://www.instagram.com/p/CnY16h7BHcl/","https://www.instagram.com/p/CmjxcBXBr12/","https://www.instagram.com/p/CmMhqOCotdI/","https://www.instagram.com/p/CmJ60cjIcv5/","https://www.instagram.com/p/ClmQAqtIp6x/","https://www.instagram.com/p/ClWoVxhIRKY/"]'
        // iceland: '["https://www.instagram.com/p/CmhSjjFvdA-/","https://www.instagram.com/p/CnHupP7JgAW/"]'
        // indonesia: '["https://www.instagram.com/p/ChJLyrADqwj/"]'
        // crete: '["https://www.instagram.com/p/ChG2EEFs_no/"]'
        // bali: '["https://www.instagram.com/p/Chqg-2Esk-w/","https://www.instagram.com/p/Ckci0z_speE/","https://www.instagram.com/p/CjKxpYspg6d/","https://www.instagram.com/p/CH2QmYNDAzO/","https://www.instagram.com/p/CCMmctjDbtV/","https://www.instagram.com/p/CCL16kdjJQf/","https://www.instagram.com/p/CBneLP_jxOE/","https://www.instagram.com/p/CBOSs6xDGYl/","https://www.instagram.com/p/CAkjFwADTXN/","https://www.instagram.com/p/B_nwCARjjnc/","https://www.instagram.com/p/B_WKMO5j9wt/","https://www.instagram.com/p/B-5CQIWjVYl/","https://www.instagram.com/p/B7D4xpSg4Fg/","https://www.instagram.com/p/B5pQj2eD94S/","https://www.instagram.com/p/B5qVtjtnHfZ/","https://www.instagram.com/p/B3zPxjbgDZ0/","https://www.instagram.com/p/B3nHxR7J_cI/","https://www.instagram.com/p/B3aTOAIIqDW/","https://www.instagram.com/p/B3jUqWwnvr8/","https://www.instagram.com/p/B2XduU4ltYG/","https://www.instagram.com/p/B2XduVPBI3X/","https://www.instagram.com/p/B2RRKn9ishG/","https://www.instagram.com/p/Bzv1VHoHwzx/","https://www.instagram.com/p/BySmr1xn3Xw/","https://www.instagram.com/p/B2G_WZdnlnG/"]'
        // indonesia: '["https://www.instagram.com/p/ChJLyrADqwj/"]'
        // portugal: '["https://www.instagram.com/p/CeQyfmWN3V1/","https://www.instagram.com/p/B32N9NABIEu/","https://www.instagram.com/p/B3h6dkyoQ9c/"]'
        // vietnam: '["https://www.instagram.com/p/CCfuj5dj0ac/","https://www.instagram.com/p/B24B0xYB4Gz/"]'
        // USA Arizona '["https://www.instagram.com/p/CBQ7XrbADrQ/","https://www.instagram.com/p/CBLNanHDdbv/"]'
        // Jamaica: '["https://www.instagram.com/p/B_fb3QEjsHi/"]'
        // Norway: '["https://www.instagram.com/p/B-12Z9gDV8x/"]'
        // Croatia: '["https://www.instagram.com/p/B_E4URWjXxS/"]'
        // Prague: '["https://www.instagram.com/p/BZgi1RAneIS/","https://www.instagram.com/p/B11m_TGCs2z/"]'
        // brazil: '["https://www.instagram.com/p/B8e-1eWDkhc/","https://www.instagram.com/p/B3j1AOdANiX/"]'
        // austria: '["https://www.instagram.com/p/B7_OZ1ADurz/"]'
        // sri lanka: '["https://www.instagram.com/p/B3hm1_zllqD/","https://www.instagram.com/p/B2twMTwnFll/","https://www.instagram.com/p/B3UpSXohs6j/"]'
        // bora bora: '["https://www.instagram.com/p/B3iRAophzTI/","https://www.instagram.com/p/B3faq7PBj1R/","https://www.instagram.com/p/B3KxaIAhkw4/","https://www.instagram.com/p/B244epUi3rK/","https://www.instagram.com/p/B2ZL56zIGld/"]'
        // Thailand cofifi: '["https://www.instagram.com/p/B3ukTYLBx9o/","https://www.instagram.com/p/B3nAj1eh7-J/","https://www.instagram.com/p/B3TYiU9h9ET/","https://www.instagram.com/p/B3eG2X9B3oF/","https://www.instagram.com/p/B3U2pFHBAJx/","https://www.instagram.com/p/B3WQ8GPBcZO/","https://www.instagram.com/p/B2_MkTygNVA/","https://www.instagram.com/p/B2_MHcBBedb/","https://www.instagram.com/p/B2KAzBrh4aE/","https://www.instagram.com/p/B2T4Q1nlGR8/","https://www.instagram.com/p/B2WUkhMh-Mq/","https://www.instagram.com/p/B2JAfpahsEX/","https://www.instagram.com/p/B2Wbp6hlFI1/","https://www.instagram.com/p/B1sUH2PBgN4/","https://www.instagram.com/p/B1qnyfkhlGb/","https://www.instagram.com/p/B11iRT-nSeb/","https://www.instagram.com/p/B1wbhYQI40y/"]'
        // Thailand Ko-Tao: '["https://www.instagram.com/p/B3tzS8iB2Ow/","https://www.instagram.com/p/B3IdTIBBPDo/","https://www.instagram.com/p/B3D_sTqB9cL/"]'
        // Thailand Krabi: '["https://www.instagram.com/p/B3sHv-thRY5/","https://www.instagram.com/p/B3lkUTahHv2/","https://www.instagram.com/p/B3L6x1ThfEJ/","https://www.instagram.com/p/B2__sF5BxO8/","https://www.instagram.com/p/B2iku2TBBAx/","https://www.instagram.com/p/B2WlpPjngl2/","https://www.instagram.com/p/B2PCotMIKBr/","https://www.instagram.com/p/B1OFo82h367/","https://www.instagram.com/p/B2VubyChmh0/","https://www.instagram.com/p/B1JTMI1hG2x/","https://www.instagram.com/p/B1nZBxPhIpE/","https://www.instagram.com/p/B1xsHPxBmeB/","https://www.instagram.com/p/B14FL0iHNt0/","https://www.instagram.com/p/B1gR2Fzlo7X/","https://www.instagram.com/p/B2JkMSED-J5/","https://www.instagram.com/p/B2WHKxCJjvp/","https://www.instagram.com/p/B1vwo9qF_B7/","https://www.instagram.com/p/B1i1ZQAB79i/","https://www.instagram.com/p/B1L6xDjIQzo/","https://www.instagram.com/p/B1bdpcOI4S_/","https://www.instagram.com/p/B0-dfjKhAvy/","https://www.instagram.com/p/B1Yj5_lhfuG/","https://www.instagram.com/p/B1yT797hh67/","https://www.instagram.com/p/Beo0mHiBsUm/","https://www.instagram.com/p/BwR0iBpFaxA/","https://www.instagram.com/p/BuJRAYhHckl/","https://www.instagram.com/p/BUFHyMGgHoI/","https://www.instagram.com/p/Bo6nDs_gQri/","https://www.instagram.com/p/BnYBID4H4fi/","https://www.instagram.com/p/BGltJYaLJCK/"]'
        // Thailand Ko-Samui: '["https://www.instagram.com/p/BzsFLn6ANup/","https://www.instagram.com/p/B0sbph7gFEk/","https://www.instagram.com/p/B05a3f-nXRc/","https://www.instagram.com/p/B19DnPoB5k2/","https://www.instagram.com/p/B2dapD6nZGb/","https://www.instagram.com/p/B3pTFs6hDoy/","https://www.instagram.com/p/B1S2D4HlfbM/","https://www.instagram.com/p/B1qrEFSlzfa/","https://www.instagram.com/p/B1Ygc2Ti2eE/","https://www.instagram.com/p/B1x9XAPg-uV/","https://www.instagram.com/p/B1diWtUoLNK/"]'
        // Sychel: '["https://www.instagram.com/p/B2rI2BoBMLv/","https://www.instagram.com/p/BzLe2YtnX6f/"]'
        // Thailand Poket: '["https://www.instagram.com/p/B3bsBx9HlbU/","https://www.instagram.com/p/B1wfwG4hdJo/","https://www.instagram.com/p/B11Nn9loYVY/"]'
        // Thailand Bangkok: '["https://www.instagram.com/p/B3Glv7LhThv/","https://www.instagram.com/p/B2Y7eSdFG3W/","https://www.instagram.com/p/B2DPWM6gIjZ/","https://www.instagram.com/p/B2Gk7W7IGAC/","https://www.instagram.com/p/B2EBekpA8iO/","https://www.instagram.com/p/B2DrWP5I0Bt/","https://www.instagram.com/p/B1VbaQGgoHX/","https://www.instagram.com/p/BuUxkQ3H5Cn/","https://www.instagram.com/p/BsSn7QIFh_Z/","https://www.instagram.com/p/B02Md_UAgw0/","https://www.instagram.com/p/B0DlKYZnxDg/","https://www.instagram.com/p/B0BNBl8JeGJ/","https://www.instagram.com/p/B1MVi_AC-B4/","https://www.instagram.com/p/BtIK8icnWav/","https://www.instagram.com/p/B1aRx2zlDYy/","https://www.instagram.com/p/BsvF98vh9cW/","https://www.instagram.com/p/ByRVgvYFYeP/","https://www.instagram.com/p/Bz-uAxDH6qZ/","https://www.instagram.com/p/B0FidPFAdfR/","https://www.instagram.com/p/BweGH1knTF1/","https://www.instagram.com/p/BvKN0hrgJLC/"]'
        // Bahamas: '["https://www.instagram.com/p/B3DtfWnBVl2/"]'
        // Vegas: '["https://www.instagram.com/p/B25SxuCBUge/"]'
        // The dominican republic: '["https://www.instagram.com/p/B2-wQDAA-cx/"]'
        // amsterdam: '["https://www.instagram.com/p/B18RMimBa8m/","https://www.instagram.com/p/ByYb3zVBfvB/","https://www.instagram.com/p/B1wH6cliNkg/","https://www.instagram.com/p/BzrQe7ypCVb/","https://www.instagram.com/p/B0TAoyyJxXZ/","https://www.instagram.com/p/B2UbFQRCNQH/","https://www.instagram.com/p/B2UIXUdpdcZ/"]'
        // Thailand maya bay: '["https://www.instagram.com/p/B1086KOlYm0/"]'
        // Thailand ko souk: '["https://www.instagram.com/p/B1gRAyIBY4L/"]'
        // cool places: '["https://www.instagram.com/p/B2EJhfrlIvh/","https://www.instagram.com/p/B2y4F_mH73V/","https://www.instagram.com/p/B3Z83F_BRxM/","https://www.instagram.com/p/B3Ka3sngCDB/","https://www.instagram.com/p/B2_r-EOAY1E/","https://www.instagram.com/p/B2UMNq6nKTp/"]'
        */

export const saved_posts = [
    "https://www.instagram.com/p/Cno_rQ0KPq5/",
    "https://www.instagram.com/p/CnrpkPxLALQ/",
    "https://www.instagram.com/p/CidODn8rbzd/",
    "https://www.instagram.com/p/CjANW5IoZ0K/",
    "https://www.instagram.com/p/CjGRiXJoNkp/",
    "https://www.instagram.com/p/CjPiLbHI19I/",
    "https://www.instagram.com/p/CnESev4JeGf/",
    "https://www.instagram.com/p/CnpWBKHJU7R/",
    "https://www.instagram.com/p/CnSTv5-JSaj/",
    "https://www.instagram.com/p/CegS2lvj-sS/",
    "https://www.instagram.com/p/Cmy5DihvtSr/",
    "https://www.instagram.com/p/CnUbz3ZLHGn/",
    "https://www.instagram.com/p/Cm4DIL8IL1d/",
    "https://www.instagram.com/p/Ck0rXb4jLPs/",
    "https://www.instagram.com/p/CloYRUuI1bF/",
    "https://www.instagram.com/p/Ci66zEUIqni/",
    "https://www.instagram.com/p/CizQePPoLs9/",
    "https://www.instagram.com/p/B9reNaRh8HO/",
    "https://www.instagram.com/p/B8EkxiIBenV/",
    "https://www.instagram.com/p/B6VT552hnpU/",
    "https://www.instagram.com/p/B8bKtbHDv0P/",
    "https://www.instagram.com/p/B3nwXhTAKLR/",
    "https://www.instagram.com/p/BsrOyfYA7j4/",
    "https://www.instagram.com/p/BzHSJ55AbQi/",
    "https://www.instagram.com/p/B8V_suFFm6X/",
    "https://www.instagram.com/p/B2w8mHVC7dB/",
    "https://www.instagram.com/p/BxyuZhSHe0cftNPqgwBSX_dnO4fKxC7Yzg0uI80/",
    "https://www.instagram.com/p/ByEy3SrnwTKmY-_EDWAvDSzVA2oKeoqKVFEOhM0/",
    "https://www.instagram.com/p/ByFSx4ynk3g_jh4ehlP4pEC3XuaCFVa6byGpFk0/",
    "https://www.instagram.com/p/ByIL_FNn_itUFtPJdk5X4nFIs074QKhpQcDYOs0/",
    "https://www.instagram.com/p/ByKCy4BngsYPj9NQxZ_3s_Ykj4AGikfYWfWnII0/",
    "https://www.instagram.com/p/ByKYdvrnJT2rCjj3yluwLh5H0oiReNLRn9hSsw0/",
    "https://www.instagram.com/p/ByNg60NH9cS74bOzZllZq4WI4QqY2jqQX_Gy8Q0/",
    "https://www.instagram.com/p/ByU1V5FHCxrRdqFw2KjBphpzJU-Bx9o_2flCkc0/",
    "https://www.instagram.com/p/B8EkxiIBenV/",
    "https://www.instagram.com/p/B8RhHY3BoUw/",
    "https://www.instagram.com/p/B8Rkic1B5mB/",
    "https://www.instagram.com/p/B8UJg2WB_IU/",
    "https://www.instagram.com/p/Cm9SAp8DqL3/",
    "https://www.instagram.com/p/Cl7iPWDDX-E/",
    "https://www.instagram.com/p/CoDcIHvgf6K/",
    "https://www.instagram.com/p/CneRc2IhEJ_/",
    "https://www.instagram.com/p/CnZkhlAPsDD/",
    "https://www.instagram.com/p/Cj5HWZlIt1N/",
    "https://www.instagram.com/p/B2L_mOeAm_1/",
    "https://www.instagram.com/p/B2SKHwCIUH7/",
    "https://www.instagram.com/p/BvUp7SWn6CO/",
    "https://www.instagram.com/p/BwXfpxjndnE/",
    "https://www.instagram.com/p/B2Zu5WuBLyW/",
    "https://www.instagram.com/p/B2XKvzsie1T/",
    "https://www.instagram.com/p/B2W3PzZAshw/",
    "https://www.instagram.com/p/B2WcGUkIReT/",
    "https://www.instagram.com/p/B2YYkGziYks/",
    "https://www.instagram.com/p/B2PKgkAoTRg/",
    "https://www.instagram.com/p/B2RuvR7BLzl/",
    "https://www.instagram.com/p/B167KYpCpFp/",
    "https://www.instagram.com/p/B2SXXH2I_A9/",
    "https://www.instagram.com/p/B2HHgsOIk5C/",
    "https://www.instagram.com/p/B2TbMl1IK5X/",
    "https://www.instagram.com/p/B19X7C4CaeQ/",
    "https://www.instagram.com/p/B2UPzlDFjR3/",
    "https://www.instagram.com/p/B19Zxf4oFzc/",
    "https://www.instagram.com/p/B2UeS2ChWVx/",
    "https://www.instagram.com/p/B1_zL4tokgx/",
    "https://www.instagram.com/p/B2CV3emAgOB/",
    "https://www.instagram.com/p/B2GfziohaWC/",
    "https://www.instagram.com/p/B2Oba1IDpi3/",
    "https://www.instagram.com/p/B2RGCfRoGgh/",
    "https://www.instagram.com/p/B2MeVZEolQP/",
    "https://www.instagram.com/p/B2JUrnEIRVV/",
    "https://www.instagram.com/p/B2PMM2JFZ8k/",
    "https://www.instagram.com/p/B2WXbigi_An/",
    "https://www.instagram.com/p/B2FRZcQC84D/",
    "https://www.instagram.com/p/B2QuH7DIuPn/",
    "https://www.instagram.com/p/B2FeOmhH_Hp/",
    "https://www.instagram.com/p/B2PPpa-pi86/",
    "https://www.instagram.com/p/CnDNBK2OWRc/",
    "https://www.instagram.com/p/CgJcuhosMhb/",
    "https://www.instagram.com/p/CB5j4HQDaKz/",
    "https://www.instagram.com/p/B-9FgbgDlwH/",
    "https://www.instagram.com/p/B60xeNPDEV4/",
    "https://www.instagram.com/p/B3lCBvKIah0/",
    "https://www.instagram.com/p/B3howWAH4cT/",
    "https://www.instagram.com/p/B3nIvA9HeBc/",
    "https://www.instagram.com/p/Cn4jKihOVxu/",
    "https://www.instagram.com/p/CnpG43oAtdQ/",
    "https://www.instagram.com/p/CSY3UfSLHZC/",
    "https://www.instagram.com/p/CFRnrYjjZkz/",
    "https://www.instagram.com/p/CAv4sAIjUlz/",
    "https://www.instagram.com/p/B1yQQHYlFIC/",
    "https://www.instagram.com/p/B2EJhfrlIvh/",
    "https://www.instagram.com/p/Bzk7Hu3nszv/",
    "https://www.instagram.com/p/Bz0ijMunsCb/",
    "https://www.instagram.com/p/B2ZMnSllPAw/",
    "https://www.instagram.com/p/Cn4RzuPoq1y/",
    "https://www.instagram.com/p/Cnpm6atgrto/",
    "https://www.instagram.com/p/CfcKBv6sdq7/",
    "https://www.instagram.com/p/Bqu0r9BBwG4/",
    "https://www.instagram.com/p/B7dMTmHjNc4/",
    "https://www.instagram.com/p/B3fAE99gnFd/",
    "https://www.instagram.com/p/BzQSyIMnHS9/",
    "https://www.instagram.com/p/B3gxCouhngx/",
    "https://www.instagram.com/p/B3KITN5BgMw/",
    "https://www.instagram.com/p/B2mFNmOhzIV/",
    "https://www.instagram.com/p/B1nj9zug9j8/",
    "https://www.instagram.com/p/B2RPh_ggCnY/",
    "https://www.instagram.com/p/B2ZIj7PB8L6/",
    "https://www.instagram.com/p/B2QAHT5I092/",
    "https://www.instagram.com/p/B2J73GGhQCO/",
    "https://www.instagram.com/p/BzgYSLdH_Oj/",
    "https://www.instagram.com/p/BziTzZHns83/",
    "https://www.instagram.com/p/BzndZJ7Hujf/",
    "https://www.instagram.com/p/B1eHUWdgOmq/",
    "https://www.instagram.com/p/B1iilCxAygW/",
    "https://www.instagram.com/p/BziTzZHns83/",
    "https://www.instagram.com/p/B7dMTmHjNc4/",
    "https://www.instagram.com/p/BzQSyIMnHS9/",
    "https://www.instagram.com/p/Bqu0r9BBwG4/",
    "https://www.instagram.com/p/CfhCyotpfBS/",
    "https://www.instagram.com/p/CfMpPg2sAgp/",
    "https://www.instagram.com/p/CdaGP_ALWjb/",
    "https://www.instagram.com/p/CdGc4L_pw21/",
    "https://www.instagram.com/p/CfI9keGh-9a/",
    "https://www.instagram.com/p/ChKf7bRoqyd/",
    "https://www.instagram.com/p/ChxIwFtIjPq/",
    "https://www.instagram.com/p/Camb_sIpO-C/",
    "https://www.instagram.com/p/CgoY1D7qBBQ/",
    "https://www.instagram.com/p/CjvsWisKt31/",
    "https://www.instagram.com/p/CkfqEv1rOFl/",
    "https://www.instagram.com/p/ClRDotgIevw/",
    "https://www.instagram.com/p/CUiDH2oh1QV/",
    "https://www.instagram.com/p/CcpxE6kJ9qG/",
    "https://www.instagram.com/p/CdrRuZcrqOc/",
    "https://www.instagram.com/p/Ce1IVVcLPB1/",
    "https://www.instagram.com/p/CfYkV9yhi7E/",
    "https://www.instagram.com/p/CfI9keGh-9a/",
    "https://www.instagram.com/p/CYfEehkD-1C/",
    "https://www.instagram.com/p/CZxHt5xNQUV/",
    "https://www.instagram.com/p/Cc1gI4rpY4o/",
    "https://www.instagram.com/p/CdGc4L_pw21/",
    "https://www.instagram.com/p/CdaGP_ALWjb/",
    "https://www.instagram.com/p/CdgBAProsJv/",
    "https://www.instagram.com/p/CdvOLCYjrdM/",
    "https://www.instagram.com/p/CeQda5qMOpx/",
    "https://www.instagram.com/p/Ce0_9OdAmto/",
    "https://www.instagram.com/p/CfJBpW9LqnL/",
    "https://www.instagram.com/p/CfJ3V4bpZUS/",
    "https://www.instagram.com/p/CfI8yGTh0dO/",
    "https://www.instagram.com/p/CfEM3bBBqHF/",
    "https://www.instagram.com/p/CfNujp8hzs1/",
    "https://www.instagram.com/p/CfMpPg2sAgp/",
    "https://www.instagram.com/p/CfUlDtJDHm4/",
    "https://www.instagram.com/p/CfUPnlmKqTq/",
    "https://www.instagram.com/p/CfbBBgoNudY/",
    "https://www.instagram.com/p/Cfbx9Y5MC6u/",
    "https://www.instagram.com/p/CfiRIUfDsak/",
    "https://www.instagram.com/p/CfjTwexhF5F/",
    "https://www.instagram.com/p/CfhCyotpfBS/",
    "https://www.instagram.com/p/CfzM1hOj1gw/",
    "https://www.instagram.com/p/CniuNCLPJ-S/",
    "https://www.instagram.com/p/CnhOUQ9qVRY/",
    "https://www.instagram.com/p/CnXsQOCMig6/",
    "https://www.instagram.com/p/CloMMk5sfHP/",
    "https://www.instagram.com/p/ChRGGG-MF0W/",
    "https://www.instagram.com/p/CmvR_5mMyO5/",
    "https://www.instagram.com/p/Cm7CGclh91t/",
    "https://www.instagram.com/p/CnfGBIxhAxa/",
    "https://www.instagram.com/p/CnckxNqhOUH/",
    "https://www.instagram.com/p/CnaRNc0gRxk/",
    "https://www.instagram.com/p/ChQOZHpDBwe/",
    "https://www.instagram.com/p/ChtHuMDs3Mc/",
    "https://www.instagram.com/p/Cmy3G79hA0q/",
    "https://www.instagram.com/p/CmPDhKHIxN_/",
    "https://www.instagram.com/p/B3O5svineQg/",
    "https://www.instagram.com/p/CnepSeRhZQs/",
    "https://www.instagram.com/p/CnTttLxBuB-/",
    "https://www.instagram.com/p/CnRq8Y_hGQO/",
    "https://www.instagram.com/p/CnJwm2ahet1/",
    "https://www.instagram.com/p/Cg8aGLzDZA9/",
    "https://www.instagram.com/p/CnZXVuDqme8/",
    "https://www.instagram.com/p/B8JrIO7DRav/",
    "https://www.instagram.com/p/Bxcb7oxHk2W/",
    "https://www.instagram.com/p/B3L5lU9I7MS/",
    "https://www.instagram.com/p/B2ykVJUn8Qh/",
    "https://www.instagram.com/p/CnZU1OYBKjx/",
    "https://www.instagram.com/p/CiPt06moctE/",
    "https://www.instagram.com/p/Ch9TfiuoAe5/",
    "https://www.instagram.com/p/ChrKcLtIrMO/",
    "https://www.instagram.com/p/ChwRUUqIdbu/",
    "https://www.instagram.com/p/Bzn6Hatnxnq/",
    "https://www.instagram.com/p/CnY16h7BHcl/",
    "https://www.instagram.com/p/CmjxcBXBr12/",
    "https://www.instagram.com/p/CmMhqOCotdI/",
    "https://www.instagram.com/p/CmJ60cjIcv5/",
    "https://www.instagram.com/p/ClmQAqtIp6x/",
    "https://www.instagram.com/p/ClWoVxhIRKY/",
    "https://www.instagram.com/p/CmhSjjFvdA-/",
    "https://www.instagram.com/p/CnHupP7JgAW/",
    "https://www.instagram.com/p/ChJLyrADqwj/",
    "https://www.instagram.com/p/ChG2EEFs_no/",
    "https://www.instagram.com/p/Chqg-2Esk-w/",
    "https://www.instagram.com/p/Ckci0z_speE/",
    "https://www.instagram.com/p/CjKxpYspg6d/",
    "https://www.instagram.com/p/CH2QmYNDAzO/",
    "https://www.instagram.com/p/CCMmctjDbtV/",
    "https://www.instagram.com/p/CCL16kdjJQf/",
    "https://www.instagram.com/p/CBneLP_jxOE/",
    "https://www.instagram.com/p/CBOSs6xDGYl/",
    "https://www.instagram.com/p/CAkjFwADTXN/",
    "https://www.instagram.com/p/B_nwCARjjnc/",
    "https://www.instagram.com/p/B_WKMO5j9wt/",
    "https://www.instagram.com/p/B-5CQIWjVYl/",
    "https://www.instagram.com/p/B7D4xpSg4Fg/",
    "https://www.instagram.com/p/B5pQj2eD94S/",
    "https://www.instagram.com/p/B5qVtjtnHfZ/",
    "https://www.instagram.com/p/B3zPxjbgDZ0/",
    "https://www.instagram.com/p/B3nHxR7J_cI/",
    "https://www.instagram.com/p/B3aTOAIIqDW/",
    "https://www.instagram.com/p/B3jUqWwnvr8/",
    "https://www.instagram.com/p/B2XduU4ltYG/",
    "https://www.instagram.com/p/B2XduVPBI3X/",
    "https://www.instagram.com/p/B2RRKn9ishG/",
    "https://www.instagram.com/p/Bzv1VHoHwzx/",
    "https://www.instagram.com/p/BySmr1xn3Xw/",
    "https://www.instagram.com/p/B2G_WZdnlnG/",
    "https://www.instagram.com/p/ChJLyrADqwj/",
    "https://www.instagram.com/p/CeQyfmWN3V1/",
    "https://www.instagram.com/p/B32N9NABIEu/",
    "https://www.instagram.com/p/B3h6dkyoQ9c/",
    "https://www.instagram.com/p/CCfuj5dj0ac/",
    "https://www.instagram.com/p/B24B0xYB4Gz/",
    "https://www.instagram.com/p/CBQ7XrbADrQ/",
    "https://www.instagram.com/p/CBLNanHDdbv/",
    "https://www.instagram.com/p/B_fb3QEjsHi/",
    "https://www.instagram.com/p/B-12Z9gDV8x/",
    "https://www.instagram.com/p/B_E4URWjXxS/",
    "https://www.instagram.com/p/BZgi1RAneIS/",
    "https://www.instagram.com/p/B11m_TGCs2z/",
    "https://www.instagram.com/p/B8e-1eWDkhc/",
    "https://www.instagram.com/p/B3j1AOdANiX/",
    "https://www.instagram.com/p/B7_OZ1ADurz/",
    "https://www.instagram.com/p/B3hm1_zllqD/",
    "https://www.instagram.com/p/B2twMTwnFll/",
    "https://www.instagram.com/p/B3UpSXohs6j/",
    "https://www.instagram.com/p/B3iRAophzTI/",
    "https://www.instagram.com/p/B3faq7PBj1R/",
    "https://www.instagram.com/p/B3KxaIAhkw4/",
    "https://www.instagram.com/p/B244epUi3rK/",
    "https://www.instagram.com/p/B2ZL56zIGld/",
    "https://www.instagram.com/p/B3ukTYLBx9o/",
    "https://www.instagram.com/p/B3nAj1eh7-J/",
    "https://www.instagram.com/p/B3TYiU9h9ET/",
    "https://www.instagram.com/p/B3eG2X9B3oF/",
    "https://www.instagram.com/p/B3U2pFHBAJx/",
    "https://www.instagram.com/p/B3WQ8GPBcZO/",
    "https://www.instagram.com/p/B2_MkTygNVA/",
    "https://www.instagram.com/p/B2_MHcBBedb/",
    "https://www.instagram.com/p/B2KAzBrh4aE/",
    "https://www.instagram.com/p/B2T4Q1nlGR8/",
    "https://www.instagram.com/p/B2WUkhMh-Mq/",
    "https://www.instagram.com/p/B2JAfpahsEX/",
    "https://www.instagram.com/p/B2Wbp6hlFI1/",
    "https://www.instagram.com/p/B1sUH2PBgN4/",
    "https://www.instagram.com/p/B1qnyfkhlGb/",
    "https://www.instagram.com/p/B11iRT-nSeb/",
    "https://www.instagram.com/p/B1wbhYQI40y/",
    "https://www.instagram.com/p/B3tzS8iB2Ow/",
    "https://www.instagram.com/p/B3IdTIBBPDo/",
    "https://www.instagram.com/p/B3D_sTqB9cL/",
    "https://www.instagram.com/p/B3sHv-thRY5/",
    "https://www.instagram.com/p/B3lkUTahHv2/",
    "https://www.instagram.com/p/B3L6x1ThfEJ/",
    "https://www.instagram.com/p/B2__sF5BxO8/",
    "https://www.instagram.com/p/B2iku2TBBAx/",
    "https://www.instagram.com/p/B2WlpPjngl2/",
    "https://www.instagram.com/p/B2PCotMIKBr/",
    "https://www.instagram.com/p/B1OFo82h367/",
    "https://www.instagram.com/p/B2VubyChmh0/",
    "https://www.instagram.com/p/B1JTMI1hG2x/",
    "https://www.instagram.com/p/B1nZBxPhIpE/",
    "https://www.instagram.com/p/B1xsHPxBmeB/",
    "https://www.instagram.com/p/B14FL0iHNt0/",
    "https://www.instagram.com/p/B1gR2Fzlo7X/",
    "https://www.instagram.com/p/B2JkMSED-J5/",
    "https://www.instagram.com/p/B2WHKxCJjvp/",
    "https://www.instagram.com/p/B1vwo9qF_B7/",
    "https://www.instagram.com/p/B1i1ZQAB79i/",
    "https://www.instagram.com/p/B1L6xDjIQzo/",
    "https://www.instagram.com/p/B1bdpcOI4S_/",
    "https://www.instagram.com/p/B0-dfjKhAvy/",
    "https://www.instagram.com/p/B1Yj5_lhfuG/",
    "https://www.instagram.com/p/B1yT797hh67/",
    "https://www.instagram.com/p/Beo0mHiBsUm/",
    "https://www.instagram.com/p/BwR0iBpFaxA/",
    "https://www.instagram.com/p/BuJRAYhHckl/",
    "https://www.instagram.com/p/BUFHyMGgHoI/",
    "https://www.instagram.com/p/Bo6nDs_gQri/",
    "https://www.instagram.com/p/BnYBID4H4fi/",
    "https://www.instagram.com/p/BGltJYaLJCK/",
    "https://www.instagram.com/p/BzsFLn6ANup/",
    "https://www.instagram.com/p/B0sbph7gFEk/",
    "https://www.instagram.com/p/B05a3f-nXRc/",
    "https://www.instagram.com/p/B19DnPoB5k2/",
    "https://www.instagram.com/p/B2dapD6nZGb/",
    "https://www.instagram.com/p/B3pTFs6hDoy/",
    "https://www.instagram.com/p/B1S2D4HlfbM/",
    "https://www.instagram.com/p/B1qrEFSlzfa/",
    "https://www.instagram.com/p/B1Ygc2Ti2eE/",
    "https://www.instagram.com/p/B1x9XAPg-uV/",
    "https://www.instagram.com/p/B1diWtUoLNK/",
    "https://www.instagram.com/p/B2rI2BoBMLv/",
    "https://www.instagram.com/p/BzLe2YtnX6f/",
    "https://www.instagram.com/p/B3bsBx9HlbU/",
    "https://www.instagram.com/p/B1wfwG4hdJo/",
    "https://www.instagram.com/p/B11Nn9loYVY/",
    "https://www.instagram.com/p/B3Glv7LhThv/",
    "https://www.instagram.com/p/B2Y7eSdFG3W/",
    "https://www.instagram.com/p/B2DPWM6gIjZ/",
    "https://www.instagram.com/p/B2Gk7W7IGAC/",
    "https://www.instagram.com/p/B2EBekpA8iO/",
    "https://www.instagram.com/p/B2DrWP5I0Bt/",
    "https://www.instagram.com/p/B1VbaQGgoHX/",
    "https://www.instagram.com/p/BuUxkQ3H5Cn/",
    "https://www.instagram.com/p/BsSn7QIFh_Z/",
    "https://www.instagram.com/p/B02Md_UAgw0/",
    "https://www.instagram.com/p/B0DlKYZnxDg/",
    "https://www.instagram.com/p/B0BNBl8JeGJ/",
    "https://www.instagram.com/p/B1MVi_AC-B4/",
    "https://www.instagram.com/p/BtIK8icnWav/",
    "https://www.instagram.com/p/B1aRx2zlDYy/",
    "https://www.instagram.com/p/BsvF98vh9cW/",
    "https://www.instagram.com/p/ByRVgvYFYeP/",
    "https://www.instagram.com/p/Bz-uAxDH6qZ/",
    "https://www.instagram.com/p/B0FidPFAdfR/",
    "https://www.instagram.com/p/BweGH1knTF1/",
    "https://www.instagram.com/p/BvKN0hrgJLC/",
    "https://www.instagram.com/p/B3DtfWnBVl2/",
    "https://www.instagram.com/p/B25SxuCBUge/",
    "https://www.instagram.com/p/B2-wQDAA-cx/",
    "https://www.instagram.com/p/B18RMimBa8m/",
    "https://www.instagram.com/p/ByYb3zVBfvB/",
    "https://www.instagram.com/p/B1wH6cliNkg/",
    "https://www.instagram.com/p/BzrQe7ypCVb/",
    "https://www.instagram.com/p/B0TAoyyJxXZ/",
    "https://www.instagram.com/p/B2UbFQRCNQH/",
    "https://www.instagram.com/p/B2UIXUdpdcZ/",
    "https://www.instagram.com/p/B1086KOlYm0/",
    "https://www.instagram.com/p/B1gRAyIBY4L/",
    "https://www.instagram.com/p/B2EJhfrlIvh/",
    "https://www.instagram.com/p/B2y4F_mH73V/",
    "https://www.instagram.com/p/B3Z83F_BRxM/",
    "https://www.instagram.com/p/B3Ka3sngCDB/",
    "https://www.instagram.com/p/B2_r-EOAY1E/",
    "https://www.instagram.com/p/B2UMNq6nKTp/",
];