export const TEMPLATES_USER_NAME = "templates";
export const POPULAR_PLAYERS = [
  'Dejounte Murray',
  'Duncan Robinson',
  'Will Barton',
  'Patrick Beverley',
  'Harrison Barnes',
  'Otto Porter Jr.',
  'Derrick Favors',
  'Lou Williams',
  'Serge Ibaka',
  'Spencer Dinwiddie',
  'Paul Millsap',
  'Joe Harris',
  'Marc Gasol',
  'Buddy Hield',
  'Ricky Rubio',
  'Eric Gordon',
  'Montrezl Harrell',
  'Jerami Grant',
  'Joe Ingles',
  'Gary Harris',
  'Zach LaVine',
  'Deandre Ayton',
  'OG Anunoby',
  'Brook Lopez',
  'JJ Redick',
  'Clint Capela',
  'Marcus Smart',
  'Eric Bledsoe',
  'Robert Covington',
  'Al Horford',
  'Jaren Jackson Jr.',
  'Shai Gilgeous-Alexander',
  'Caris LeVert',
  'Aaron Gordon',
  'Myles Turner',
  'John Collins',
  'Andre Drummond',
  'Fred VanVleet',
  'Domantas Sabonis',
  'Malcolm Brogdon',
  'Gordon Hayward',
  'Tobias Harris',
  'John Wall',
  'Mike Conley',
  'Danilo Gallinari',
  'Steven Adams',
  'Kevin Love',
  'Blake Griffin',
  'Victor Oladipo',
  'Ja Morant',
  'Kristaps Porzingis',
  'DeMar DeRozan',
  'Jaylen Brown',
  'Brandon Ingram',
  'CJ McCollum',
  'Draymond Green',
  'LaMarcus Aldridge',
  'Zion Williamson',
  'Kemba Walker',
  'Pascal Siakam',
  'Trae Young',
  'Kyle Lowry',
  'Khris Middleton',
  'Jrue Holiday',
  'Russell Westbrook',
  'Devin Booker',
  'Donovan Mitchell',
  'Jamal Murray',
  'Ben Simmons',
  'Bam Adebayo',
  'Kyrie Irving',
  'Karl-Anthony Towns',
  'Jayson Tatum',
  'Rudy Gobert',
  'Bradley Beal',
  'Chris Paul',
  'Paul George',
  'Damian Lillard',
  'Jimmy Butler',
  'Joel Embiid',
  'Kevin Durant',
  'Stephen Curry',
  'James Harden',
  'Kawhi Leonard',
  'Giannis Antetokounmpo',
  'LeBron James',
  'Jonas Valanciunas',
  'Davis Bertans',
  'T.J. Warren',
  'Goran Dragic',
  'Bogdan Bogdanovic',
  'P.J. Tucker',
  'Bojan Bogdanovic',
  "D'Angelo Russell",
  'Jusuf Nurkic',
  'Nikola Vucevic',
  "De'Aaron Fox",
  'Luka Doncic',
  'Nikola Jokic',
  'Tyler Herro',
  'Klay Thompson',
  'Seth Curry',
  'Danny Green',
  'Kyle Korver',

  // 'Tristan Thompson',
];

export const DEFAULT_USER_SETTINGS = [
  {
    name: 'AUTO_CALC_OT',
    value: '1',
  },
  {
    name: 'AUTO_CALC_OT_GAME_LENGTH',
    value: '8',
  },
  {
    name: 'SHOW_INACTIVE_PLAYERS',
    value: '0',
  },
];
