db:
  host: 'ec2-54-82-103-223.compute-1.amazonaws.com'
  username: 'uas9bbjc084te'
  password: 'p83033241adf38d781f30d4cc3e6fd53db3cdf834a5634c241737b9d7b6bb44c0'
  port: 5432,
  database: 'de0t053q74dmaj'
  synchronize: true
  extra:
    ssl:
      rejectUnauthorized: false

jwt:
  secret: 'topSecret21'
