db:
  host: 'ec2-3-217-251-77.compute-1.amazonaws.com'
  username: 'wgrczzhmdsuhsi'
  password: '57d7d8531ef77a6298725aaf10cdcd7ca20e1c205cf18791ebdc96ca659eba04'
  port: 5432,
  database: 'd3uo96btivr69d'
  synchronize: true
  extra:
    ssl:
      rejectUnauthorized: false

jwt:
  secret: 'topSecret21'