db:
  host: 'ec2-3-230-87-163.compute-1.amazonaws.com'
  username: 'qhryowlnqsgysl'
  password: '650bae8295578b5b8764d747f7f630d569597fa04dbdfe2270f46faef46b5238'
  port: 5432,
  database: 'd8irue2932ioo9'
  synchronize: true
  extra:
    ssl:
      rejectUnauthorized: false

jwt:
  secret: 'topSecret21'
