db:
  host: 'ec2-52-54-212-232.compute-1.amazonaws.com'
  username: 'jutptkovfnhejf'
  password: '8a3cb12ebcded5315de32d93924ef1898b8c57861caea210f72ef8ec976f3a52'
  port: 5432,
  database: 'da3epm0noqnaah'
  synchronize: true
  extra:
    ssl:
      rejectUnauthorized: false

jwt:
  secret: 'topSecret21'