db:
  host: 'ce4o834ee7h752.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com'
  username: 'u385lmged6ajti'
  password: 'p992b3c04046c65df342949c7255453fc4a349132cf3c647cdfc5785c442901db'
  port: 5432,
  database: 'd8bhe55suunicg'
  synchronize: true
  extra:
    ssl:
      rejectUnauthorized: false

jwt:
  secret: 'topSecret21'
